### PR TITLE
Implement retroactive validation

### PR DESCRIPTION
**Pull request by aaron-kaplan**

### CODE REVIEW

**Comment by aaron-kaplan** [comment]
- [ ] TODO: Need to do the same for PCR.

**Comment by awrobertson** [comment]
I think the probabilistic scores also need to be written out when the retroactive validation option is selected. I assume that CPT is calculating them.
This could follow what the pfv function:
  for skill in ['generalized_roc', 'ignorance', 'rank_probability_skill_score']: 
        cpt.write(437)
        cpt.write(CPT_PFV_R[skill.upper()])
        cpt.write(cpt.outputs[skill].absolute())
    cpt.wait_for_files()

    skill_values = [ open_cptdataset(str(cpt.outputs[i].absolute()) + '.txt') for i in ['generalized_roc', 'ignorance', 'rank_probability_skill_score'] ]
    skill_values = [ getattr(i, [ii for ii in i.data_vars][0]) for i in skill_values]
    for i in range(len(skill_values)):
        skill_values[i].name = ['generalized_roc', 'ignorance', 'rank_probability_skill_score'][i] 
    skill_values = xr.merge(skill_values).mean('Mode')
    return skill_values

**Comment by aaron-kaplan** [comment]
> I think the probabilistic scores also need to be written out when the retroactive validation option is selected.

It seems like you're right, and yet those scores are already present in the output even so. Turns out they're written out in [probabilistic_forecast_verification.py](https://github.com/iri-pycpt/cpt-core/blob/main/src/cptcore/functional/probabilistic_forecast_verification.py#L82-L86). Why the deterministic skill scores are calculated in the cca function but the probabilistic scores aren't is beyond me. Also the comment in p_p_v.py says "deterministic skill scores," which is a typo (deterministic --> probabilistic). I will add and fix comments to make the situation clearer.

**Comment by awrobertson** [comment]
> > I think the probabilistic scores also need to be written out when the retroactive validation option is selected.
> 
> It seems like you're right, and yet those scores are already present in the output even so. Turns out they're written out in [probabilistic_forecast_verification.py](https://github.com/iri-pycpt/cpt-core/blob/main/src/cptcore/functional/probabilistic_forecast_verification.py#L82-L86). 

The PFV function should not be called when the retroactive validation option is selected. Simon coded it so that a user could read their own set of forecasts into CPT, and verify them. Angel/Kyle used it as a work-around.

> Why the deterministic skill scores are calculated in the cca function but the probabilistic scores aren't is beyond me. 

CPT only computes deterministic skill scores when validation =  cross-validation. When validation =  retroactive, I'm pretty sure that it computes the probabilistic skill scores as well. Please check it returns them.

> Also the comment in p_p_v.py says "deterministic skill scores," which is a typo (deterministic --> probabilistic). I will add and fix comments to make the situation clearer.

Thanks, I noticed that typo too.

**Comment by aaron-kaplan** [comment]
I see. So the PFV function only exists to support the in-sample evaluation hack, and you want to stop using that hack in both the seasonal and subseasona versions, so we can just remove that function now, and make sure the CCA function saves both deterministic and (if applicable) probabilistic scores?

[edit: swapped probabilistic and deterministic in the last sentence]

**Comment by awrobertson** [comment]
> I see. So the PFV function only exists to support the in-sample evaluation hack, 

PFV is also a functionality in CPT that allows users to verify probabilistic forecasts made with other software, with CPT. That functionality may be useful to have in PyCPT as well in the future.

> and you want to stop using that hack in both the seasonal and subseasonal versions, so we can just remove that function now, and make sure the CCA function saves both deterministic and (if applicable) probabilistic scores?

A definite yes for the subseasonal version. 

An in principle yes for the seasonal version, because we need to take stock of the implications:  users may be confused why the prob scores are no longer available. I suggest holding off on changing the seasonal version (ie keep the hack) for now. As I think I mentioned before, double cross-validation is the other proper way (besides retroactive) to obtain probabilistic scores. Simon recently implemented this in CPT but I don't know if it's been fully tested yet.

**Comment by aaron-kaplan** [comment]
@awrobertson this is ready for another round of review. I have published this version to the dev conda channel, so you can test it with the current subseasonal notebook by following the instructions in https://github.com/iri-pycpt/notebooks/pull/11#issuecomment-1659406986 .

**Comment by aaron-kaplan** [comment]
@awrobertson please give this a final look. I have published it to the dev channel, and there are instructions for testing it in https://github.com/iri-pycpt/notebooks/pull/11 .

**Pull request merged**
